# Generated by Django 5.2.4 on 2026-01-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_enrollment_status_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.package'),
        ),
    ]
