# Generated by Django 5.2.4 on 2026-01-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_course_tutors_question_order_quiz_is_published_and_more'),
        ('payments', '0004_alter_payment_amount_alter_payment_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='module.course'),
        ),
    ]
