# Generated by Django 5.2.4 on 2026-01-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_package_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='account_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payout',
            name='bank_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='payout',
            name='flutterwave_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
