# Generated by Django 5.2.4 on 2026-01-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payout_account_number_payout_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='is_active',
        ),
        migrations.AddField(
            model_name='addon',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.feature'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('one-on-one research clinic', 'One-on-One research Clinic'), ('capstone project feedback', 'Capstone Project Feedback'), ('premium add-on', 'Premium Add-on')], max_length=30, null=True),
        ),
    ]
