# Generated by Django 5.2.4 on 2026-01-04 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_email_alerts_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorcourseassignment',
            name='tutor',
            field=models.OneToOneField(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
