# Generated by Django 5.2.4 on 2026-01-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_sessionattendance_session_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
