# Generated by Django 5.2.4 on 2026-01-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
