# Generated by Django 5.2.4 on 2025-09-22 01:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payouts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Course Revenues',
                'ordering': ['-revenue'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payouts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_percentage', models.CharField(max_length=10)),
                ('revenue_this_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pending_payouts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_transactions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Succeeded', 'Succeeded'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('last_aggregated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Revenue Tracking',
                'ordering': ['date'],
            },
        ),
    ]
