# Generated by Django 5.2.4 on 2025-08-27 19:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_weeks', models.IntegerField(default=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('has_video', models.BooleanField(default=False)),
                ('video_duration_minutes', models.PositiveIntegerField(default=0)),
                ('minimum_watch_percentage', models.FloatField(default=80.0)),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('quiz', 'Quiz'), ('text', 'Text')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='content_files/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='module.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('week_number', models.PositiveIntegerField(help_text='A value between 1 and 12.', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('requires_all_lessons', models.BooleanField(default=True)),
                ('requires_all_quizzes', models.BooleanField(default=True)),
                ('requires_project_submission', models.BooleanField(default=False)),
                ('requires_live_session_attendance', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='module.course')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meeting_url', models.URLField()),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('minimum_attendance_minutes', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='module.module')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='module.module'),
        ),
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submission_file', models.FileField(upload_to='capstone_projects/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('N/A', 'Not Graded')], default='N/A', help_text='Grade assigned to the capstone project.', max_length=10, null=True)),
                ('grade2', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('N/A', 'Not Graded')], default='N/A', help_text='Pass or Fail grade for the capstone project.', max_length=10, null=True)),
                ('requires_submission', models.BooleanField(default=True)),
                ('requires_peer_review', models.BooleanField(default=False)),
                ('requires_instructor_approval', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='module.module')),
            ],
            options={
                'verbose_name': 'Capstone Project',
                'verbose_name_plural': 'Capstone Projects',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_option', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('passing_score', models.FloatField(default=70.0, help_text='Passing score percentage (0.0 to 100.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed (1 to 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('is_required_for_module', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='module.lesson')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='module.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('essay', 'Essay')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='module.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='module.quizsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_module_order'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['module'], name='module_quiz_module__2dc4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lesson'], name='module_quiz_lesson__49064e_idx'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 0.0), ('passing_score__lte', 100.0)), name='quiz_passing_score_range'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 3)), name='quiz_max_attempts_range'),
        ),
    ]
