# Generated by Django 5.2.4 on 2025-08-17 08:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capstoneproject',
            options={'verbose_name': 'Capstone Project', 'verbose_name_plural': 'Capstone Projects'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module', 'order']},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'verbose_name': 'Live Session', 'verbose_name_plural': 'Live Sessions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='grade2',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('N/A', 'Not Graded')], default='N/A', help_text='Pass or Fail grade for the capstone project.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='module.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='requires_instructor_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='requires_peer_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='requires_submission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='minimum_watch_percentage',
            field=models.FloatField(default=80.0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='minimum_attendance_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='requires_all_lessons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='requires_all_quizzes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='requires_live_session_attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='requires_project_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_required_for_module',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed (1 to 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.FloatField(default=70.0, help_text='Passing score percentage (0.0 to 100.0).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='capstoneproject',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('N/A', 'Not Graded')], default='N/A', help_text='Grade assigned to the capstone project.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='week_number',
            field=models.PositiveIntegerField(help_text='A value between 1 and 12.', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='module.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='module.module'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['module'], name='module_quiz_module__2dc4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lesson'], name='module_quiz_lesson__49064e_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='unique_module_order'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('passing_score__gte', 0.0), ('passing_score__lte', 100.0)), name='quiz_passing_score_range'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 3)), name='quiz_max_attempts_range'),
        ),
    ]
