# Generated by Django 5.2.4 on 2026-01-01 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_certificate_certificatepayment_and_more'),
        ('users', '0006_customuser_email_alerts_customuser_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'tutor'}, related_name='courses_as_tutor', through='users.TutorCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='module.course'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked'), ('payment_pending', 'Payment_pending'), ('payment_failed', 'Payment_failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='certificaterequest',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_certificate_request'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='module.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatepayment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_payments', to='module.course'),
        ),
        migrations.AddField(
            model_name='certificatepayment',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_marked_certificate_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificaterevocationlog',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revocation_logs', to='module.certificate'),
        ),
        migrations.AddField(
            model_name='certificaterevocationlog',
            name='revoked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='module.course'),
        ),
        migrations.AddField(
            model_name='livesessionattendance',
            name='live_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_attendances', to='module.livesession'),
        ),
        migrations.AddField(
            model_name='livesessionattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='module.course'),
        ),
        migrations.AddField(
            model_name='resource',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='module.module'),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceactivity',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='module.resource'),
        ),
        migrations.AddField(
            model_name='resourceactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AddConstraint(
            model_name='certificatepayment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_certificate_payment'),
        ),
        migrations.AlterUniqueTogether(
            name='courseobjective',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='livesessionattendance',
            unique_together={('student', 'live_session')},
        ),
        migrations.AddIndex(
            model_name='resourceactivity',
            index=models.Index(fields=['resource', 'action'], name='module_reso_resourc_1bba57_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceactivity',
            index=models.Index(fields=['user'], name='module_reso_user_id_120cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceactivity',
            index=models.Index(fields=['created_at'], name='module_reso_created_807b4a_idx'),
        ),
    ]
