# Generated by Django 5.2.4 on 2026-01-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_course_tutors_question_order_quiz_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('tutors', 'Tutors')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'External Link'), ('slide ns', 'Slides'), ('other', 'Other')], max_length=20),
        ),
    ]
