# Generated by Django 5.2.4 on 2026-01-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_announcement_audience_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='content_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='module.contentitem'),
        ),
    ]
