# Generated by Django 5.2.4 on 2026-01-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_alter_resource_options_remove_resource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
