# Generated by Django 5.2.4 on 2026-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0010_certificaterequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked'), ('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed')], default='pending', max_length=20),
        ),
    ]
