# Generated by Django 5.2.4 on 2026-01-12 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0013_alter_quiz_max_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of attempts allowed (1 to 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
