# Generated by Django 5.2.4 on 2026-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0015_alter_quiz_max_attempts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='quiz_max_attempts_range',
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1), ('max_attempts__lte', 5)), name='quiz_max_attempts_range'),
        ),
    ]
