# Generated by Django 5.2.4 on 2026-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0016_remove_quiz_quiz_max_attempts_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points_earned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='is_finalized',
            field=models.BooleanField(default=True, help_text='False if manual grading is required and not yet completed.'),
        ),
    ]
