# Generated by Django 5.2.4 on 2026-01-13 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0017_answer_points_earned_answer_teacher_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to='module.course'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('revoked', 'Revoked'), ('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed'), ('issued', 'issued')], default='pending', max_length=20),
        ),
    ]
