# Generated by Django 5.2.4 on 2026-01-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0018_certificaterequest_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capstoneproject',
            name='module',
        ),
        migrations.CreateModel(
            name='CapstoneInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='The prompt the student must answer.')),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to='capstone_resources/')),
                ('requires_peer_review', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capstone_instructions', to='module.course')),
            ],
        ),
        migrations.AddField(
            model_name='capstoneproject',
            name='instructions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='module.capstoneinstructions'),
        ),
    ]
