# Generated by Django 5.2.4 on 2026-01-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0020_capstonefeedbackrequest_finalexam_examsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='is_fully_graded',
            field=models.BooleanField(default=False),
        ),
    ]
