# Generated by Django 5.2.4 on 2026-01-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0021_examsubmission_is_fully_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
