# Generated by Django 5.2.4 on 2026-02-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0022_contentitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='module.lesson'),
        ),
    ]
