# Generated by Django 5.2.4 on 2025-08-17 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0002_alter_capstoneproject_options_alter_lesson_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default='locked', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completion_data', models.JSONField(default=dict)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.contentitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ContentProgress',
                'verbose_name_plural': 'ContentProgresses',
                'indexes': [models.Index(fields=['student', 'state'], name='progresse_c_student_ee6f9c_idx'), models.Index(fields=['content_item', 'state'], name='progresse_c_content_bc3b27_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'content_item'), name='unique_student_content_item')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default='locked', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('video_watch_percentage', models.FloatField(default=0.0)),
                ('completion_data', models.JSONField(default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LessonProgress',
                'verbose_name_plural': 'LessonProgresses',
                'indexes': [models.Index(fields=['student', 'state'], name='progresse_l_student_83e9a6_idx'), models.Index(fields=['lesson', 'state'], name='progresse_l_lesson__415201_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson')],
            },
        ),
        migrations.CreateModel(
            name='ModuleCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default='locked', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completion_data', models.JSONField(default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ModuleCompletion',
                'verbose_name_plural': 'ModuleCompletions',
                'indexes': [models.Index(fields=['student', 'state'], name='progresse_m_student_7ae339_idx'), models.Index(fields=['module', 'state'], name='progresse_m_module__b6c14f_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'module'), name='unique_student_module')],
            },
        ),
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=30)),
                ('old_state', models.CharField(max_length=20, null=True)),
                ('new_state', models.CharField(max_length=20, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'timestamp'], name='progresse_p_student_054088_idx'), models.Index(fields=['content_type', 'content_id'], name='progresse_p_content_57e192_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default='locked', max_length=20)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_instructor_approved', models.BooleanField(default=False)),
                ('is_peer_reviewed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completion_data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='module.capstoneproject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProjectProgress',
                'verbose_name_plural': 'ProjectProgresses',
                'indexes': [models.Index(fields=['student', 'state'], name='progresse_p_student_4f3939_idx'), models.Index(fields=['project', 'state'], name='progresse_p_project_85b4c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'project'), name='unique_student_project')],
            },
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default='locked', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('best_score', models.FloatField(default=0.0)),
                ('latest_score', models.FloatField(default=0.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completion_data', models.JSONField(default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuizProgress',
                'verbose_name_plural': 'QuizProgress',
                'indexes': [models.Index(fields=['student', 'state'], name='progresse_q_student_8213e5_idx'), models.Index(fields=['quiz', 'state'], name='progresse_q_quiz_id_817703_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'quiz'), name='unique_student_quiz')],
            },
        ),
    ]
