# Generated by Django 5.2.4 on 2025-08-29 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
