# Generated by Django 5.2.4 on 2025-08-17 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_capstoneproject_options_alter_lesson_options_and_more'),
        ('progresse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modulecompletion',
            name='unique_student_module',
        ),
        migrations.AddConstraint(
            model_name='modulecompletion',
            constraint=models.UniqueConstraint(fields=('student', 'module'), name='unique_student_module'),
        ),
    ]
