# Generated by Django 5.2.4 on 2026-01-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresse', '0002_alter_contentprogress_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='current_question',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
