# Generated by Django 5.2.4 on 2026-01-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresse', '0003_quizprogress_current_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressevent',
            options={'verbose_name': 'Progress Event', 'verbose_name_plural': 'Progress Events'},
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='content_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('module', 'Module'), ('quiz', 'Quiz'), ('project', 'Project'), ('content_item', 'Content Item')], max_length=20),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='event_type',
            field=models.CharField(choices=[('state_change', 'State Change'), ('unlock', 'Unlock'), ('access_denied', 'Access Denied')], max_length=30),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='new_state',
            field=models.CharField(blank=True, choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='old_state',
            field=models.CharField(blank=True, choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], max_length=20, null=True),
        ),
    ]
