# Generated by Django 5.2.4 on 2026-01-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0019_remove_capstoneproject_module_capstoneinstructions_and_more'),
        ('progresse', '0004_alter_progressevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectprogress',
            name='unique_student_project',
        ),
        migrations.RemoveIndex(
            model_name='projectprogress',
            name='progresse_p_project_85b4c5_idx',
        ),
        migrations.RemoveField(
            model_name='projectprogress',
            name='project',
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='instructions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='module.capstoneinstructions'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_tracker', to='module.capstoneproject'),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='content_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('module', 'Module'), ('quiz', 'Quiz'), ('project', 'Project'), ('content_item', 'Content Item'), ('resource', 'Resource'), ('certificate_payment', 'Certificate_Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='event_type',
            field=models.CharField(choices=[('state_change', 'State Change'), ('unlock', 'Unlock'), ('access_denied', 'Access Denied'), ('payment_confirmed', 'Payment Confirmed'), ('viewed', 'Viewed'), ('course', 'Course')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='state',
            field=models.CharField(default='locked', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectprogress',
            index=models.Index(fields=['instructions', 'state'], name='progresse_p_instruc_0c407e_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectprogress',
            constraint=models.UniqueConstraint(fields=('student', 'instructions'), name='unique_student_project'),
        ),
    ]
