# Generated by Django 5.2.4 on 2026-01-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresse', '0005_remove_projectprogress_unique_student_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='state',
            field=models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], default='locked', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='state',
            field=models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], default='locked', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulecompletion',
            name='state',
            field=models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], default='locked', max_length=20),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='new_state',
            field=models.CharField(blank=True, choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='progressevent',
            name='old_state',
            field=models.CharField(blank=True, choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='state',
            field=models.CharField(choices=[('locked', 'locked'), ('available', 'available'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed'), ('pending', 'pending')], default='locked', max_length=20),
        ),
    ]
