# Generated by Django 5.2.4 on 2025-08-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
