# Generated by Django 5.2.4 on 2025-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('teacher', 'Teacher')], default='student', max_length=20),
        ),
    ]
