# Generated by Django 5.2.4 on 2025-08-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cohort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
